sudo: required
language: python
services:
    - docker
before_install:
    - docker pull cdent/placedock
    - docker run -t -d -p 127.0.0.1:80:80 -e "DB_SYNC=True" -e "AUTH_STRATEGY=noauth2" cdent/placedock
    - pip install gabbi
script: gabbi-run http://127.0.0.1/ -- gabbits/*.yaml
